//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascendia.Core.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascendia.Core.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugador sin nombre.
        /// </summary>
        internal static string DefaultPlayerName {
            get {
                return ResourceManager.GetString("DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil que intenta agregar ya existe..
        /// </summary>
        internal static string ErrorPlayerDuplicated {
            get {
                return ResourceManager.GetString("ErrorPlayerDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando nuevo perfil.
        /// </summary>
        internal static string ProgressAddToDb {
            get {
                return ResourceManager.GetString("ProgressAddToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelando....
        /// </summary>
        internal static string ProgressCancelling {
            get {
                return ResourceManager.GetString("ProgressCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accediendo al ladder.
        /// </summary>
        internal static string ProgressCheckLadder {
            get {
                return ResourceManager.GetString("ProgressCheckLadder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accediendo a W/L.
        /// </summary>
        internal static string ProgressCheckWinLose {
            get {
                return ResourceManager.GetString("ProgressCheckWinLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo acceder al ladder.
        /// </summary>
        internal static string ProgressPlayerNotFound {
            get {
                return ResourceManager.GetString("ProgressPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando cuenta (Refresh).
        /// </summary>
        internal static string ProgressRefreshPlayer {
            get {
                return ResourceManager.GetString("ProgressRefreshPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se llegó al límite de pedidos. Esperando para continuar (~1min).
        ///({0}/{1})..
        /// </summary>
        internal static string ProgressRequestLimitReached {
            get {
                return ResourceManager.GetString("ProgressRequestLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo acceder a W/L.
        /// </summary>
        internal static string ProgressWinLoseNotFound {
            get {
                return ResourceManager.GetString("ProgressWinLoseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando {0} de {1} perfiles.
        ///{2}.
        /// </summary>
        internal static string UpdateMemberProgressFormat {
            get {
                return ResourceManager.GetString("UpdateMemberProgressFormat", resourceCulture);
            }
        }
    }
}
