//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascendia.Discord.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmojiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmojiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascendia.Discord.Strings.EmojiResources", typeof(EmojiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438241827697197066.
        /// </summary>
        internal static string Position_Hardsupport_5 {
            get {
                return ResourceManager.GetString("Position_Hardsupport_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438241828842508440.
        /// </summary>
        internal static string Position_Midlane_2 {
            get {
                return ResourceManager.GetString("Position_Midlane_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438241829761061035.
        /// </summary>
        internal static string Position_Offlane_3 {
            get {
                return ResourceManager.GetString("Position_Offlane_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438241831237324970.
        /// </summary>
        internal static string Position_Safelane_1 {
            get {
                return ResourceManager.GetString("Position_Safelane_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438241840120991865.
        /// </summary>
        internal static string Position_Softsupport_4 {
            get {
                return ResourceManager.GetString("Position_Softsupport_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438256122929615011.
        /// </summary>
        internal static string Position_Unknown {
            get {
                return ResourceManager.GetString("Position_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242591866093649.
        /// </summary>
        internal static string Rank_0 {
            get {
                return ResourceManager.GetString("Rank_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242593384304740.
        /// </summary>
        internal static string Rank_1 {
            get {
                return ResourceManager.GetString("Rank_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242594239807558.
        /// </summary>
        internal static string Rank_2 {
            get {
                return ResourceManager.GetString("Rank_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242595842297867.
        /// </summary>
        internal static string Rank_3 {
            get {
                return ResourceManager.GetString("Rank_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438258924267634860.
        /// </summary>
        internal static string Rank_4 {
            get {
                return ResourceManager.GetString("Rank_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242597599576115.
        /// </summary>
        internal static string Rank_5 {
            get {
                return ResourceManager.GetString("Rank_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242598861930657.
        /// </summary>
        internal static string Rank_6 {
            get {
                return ResourceManager.GetString("Rank_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242599948255339.
        /// </summary>
        internal static string Rank_7 {
            get {
                return ResourceManager.GetString("Rank_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1438242600825127124.
        /// </summary>
        internal static string Rank_8 {
            get {
                return ResourceManager.GetString("Rank_8", resourceCulture);
            }
        }
    }
}
