//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascendia.Discord.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascendia.Discord.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accediendo a la lista de miembros..
        /// </summary>
        internal static string AccessingMembersList {
            get {
                return ResourceManager.GetString("AccessingMembersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot conectado..
        /// </summary>
        internal static string BotConnected {
            get {
                return ResourceManager.GetString("BotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot desconectado..
        /// </summary>
        internal static string BotDisconnected {
            get {
                return ResourceManager.GetString("BotDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id del canal no encontrado..
        /// </summary>
        internal static string ChannelIdNotFoundError {
            get {
                return ResourceManager.GetString("ChannelIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Puede encontrar el ranking completo en el siguiente Hilo :point_down:.
        /// </summary>
        internal static string FullRankingCaption {
            get {
                return ResourceManager.GetString("FullRankingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking completo {0} perfiles..
        /// </summary>
        internal static string FullRankingThreadNameFormat {
            get {
                return ResourceManager.GetString("FullRankingThreadNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay suficientes perfiles para mostrar el ranking..
        /// </summary>
        internal static string NoMembersToShow {
            get {
                return ResourceManager.GetString("NoMembersToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación ya está en progreso..
        /// </summary>
        internal static string OperationAlredyInProgress {
            get {
                return ResourceManager.GetString("OperationAlredyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación cancelada..
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelando operación....
        /// </summary>
        internal static string OperationCancelling {
            get {
                return ResourceManager.GetString("OperationCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Ranking Dota 2 - Impacto Solar (BETA)..
        /// </summary>
        internal static string RankingHeader {
            get {
                return ResourceManager.GetString("RankingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo información actualizada de perfiles....
        /// </summary>
        internal static string RefreshingMembers {
            get {
                return ResourceManager.GetString("RefreshingMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando. Por favor, espere..
        /// </summary>
        internal static string StartingOperation {
            get {
                return ResourceManager.GetString("StartingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el Hilo en este canal..
        /// </summary>
        internal static string ThreadCreationFailed {
            get {
                return ResourceManager.GetString("ThreadCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} perfiles actualizados..
        /// </summary>
        internal static string UpdatedProfilesCountFormat {
            get {
                return ResourceManager.GetString("UpdatedProfilesCountFormat", resourceCulture);
            }
        }
    }
}
