//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ascendia.Discord.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ascendia.Discord.Strings.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accediendo a la lista de miembros..
        /// </summary>
        internal static string AccessingMembersListMessage {
            get {
                return ResourceManager.GetString("AccessingMembersListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id del canal no encontrado..
        /// </summary>
        internal static string ChannelIdNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("ChannelIdNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Puede encontrar el ranking completo en el siguiente Hilo :point_down:.
        /// </summary>
        internal static string FullRankingCaptionMessage {
            get {
                return ResourceManager.GetString("FullRankingCaptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking completo {0} perfiles..
        /// </summary>
        internal static string FullRankingThreadNameMessage {
            get {
                return ResourceManager.GetString("FullRankingThreadNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay suficientes perfiles para mostrar el ranking..
        /// </summary>
        internal static string NoMembersToShowMessage {
            get {
                return ResourceManager.GetString("NoMembersToShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación ya está en progreso..
        /// </summary>
        internal static string OperationAlredyInProgressMessage {
            get {
                return ResourceManager.GetString("OperationAlredyInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación cancelada..
        /// </summary>
        internal static string OperationCancelledMessage {
            get {
                return ResourceManager.GetString("OperationCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelando operación....
        /// </summary>
        internal static string OperationCancellingMessage {
            get {
                return ResourceManager.GetString("OperationCancellingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Ranking Dota 2 - Impacto Solar..
        /// </summary>
        internal static string RankingHeaderMessage {
            get {
                return ResourceManager.GetString("RankingHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando. Por favor, espere..
        /// </summary>
        internal static string StartingOperationMessage {
            get {
                return ResourceManager.GetString("StartingOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el Hilo en este canal..
        /// </summary>
        internal static string ThreadCreationFailedMessage {
            get {
                return ResourceManager.GetString("ThreadCreationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} perfiles actualizados..
        /// </summary>
        internal static string UpdatedProfilesCountFormat {
            get {
                return ResourceManager.GetString("UpdatedProfilesCountFormat", resourceCulture);
            }
        }
    }
}
